- name: Ensure group 'developers' exists
  group:
    name: developers
    state: present

- name: Create the user 'bender'
  user:
    name: bender
    shell: /bin/bash
    password: $6$QJmzvbMhlt7C.qOO$uSkIZs/nINf2HFR/.nerO3qfRzIOR53BwZVwJspkkKdrO1KLOzIcW7hG7UWAhGTh/VJVvxhbZO7qloGqGs30E/

- name: Assign 'bender' to the 'developers' group
  user:
    name: bender
    groups: developers
    append: yes

- name: Create a directory named 'engineering'
  file:
    path: /opt/engineering
    state: directory
    mode: 0750
    group: developers

# NOTE: En replays no lo crea si ya existe, pero actualiza permisos etc.
- name: Create a file in the 'engineering' directory
  file:
    path: "/opt/engineering/private.txt"
    state: touch
    mode: 0770
    group: developers


# ---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
