apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
            value: "/etc/grafana/dashboards/telnet-server.json"
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests: 
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards
            name: grafana-dashboards
            readOnly: false
          - mountPath: /etc/grafana/dashboards/pods.json
            name: grafana-dashboard-pods
            subPath: pods.json
            readOnly: false
          - mountPath: /etc/grafana/dashboards/telnet-server.json
            name: grafana-dashboard-telnet-server
            subPath: telnet-server.json
            readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-dashboards
          configMap:
              defaultMode: 420
              name: grafana-dashboards
        - name: grafana-dashboard-pods
          configMap:
              name: grafana-dashboard-pods
        - name: grafana-dashboard-telnet-server
          configMap:
              name: grafana-dashboard-telnet-server
