apiVersion: batch/v1
kind: CronJob
metadata:
  name: bbs-warrior
  labels:
    app: bbs-warrior
    app.kubernetes.io/name: dftd
    app.kubernetes.io/component: bbs-warrior
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: bbs-warrior
        spec:
          containers:
          - name: bbs-warrior
            image: ghcr.io/bradleyd/devops_for_the_desperate/bbs-warrior:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: MAX_CONNECTIONS
              value: "500"
            - name: TELNET_HOST
              value: "telnet-server:2323"
          restartPolicy: OnFailure
