---
- name: pabloqpacin VMs
  hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  tasks:
     - import_tasks: pabloqpacin/apt_update.yml
     - import_tasks: pabloqpacin/apt_install_base.yml
     - import_tasks: pabloqpacin/apt_install_bat.yml
    #  - import_tasks: pabloqpacin/clone_and_symlink_dotfiles.yml
